services:
  app:
    image: chris3434/foodbackjenkins:latest
    container_name: back-test-container-foodapp
    ports:
      - "3600:3600"
    depends_on:
      - mysql
    environment:
      - DATABASE_NAME=fooddatabase
      - DATABASE_USER=food
      - DATABASE_PASSWORD=food
      - DATABASE_HOST=mysql
      - DATABASE_DIALECT=mysql
      - PORT=3600
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: mysql-food-v2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fooddatabase
      MYSQL_USER: food
      MYSQL_PASSWORD: food
    ports:
      - "3386:3386"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-food
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8888:80"
    depends_on:
      - mysql
    networks:
      - default

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-jc
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - monitoring

volumes:
  mysql-data:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
  default:
    driver: bridge