global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'app'
    static_configs:
      - targets: ['app:3600']

remote_write:
  - url: 'https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push'
    basic_auth:
      username: '1689171'
      password: 'glc_eyJvIjoiMTE3NTk1OSIsIm4iOiJzdGFjay05ODY3MTMtaW50ZWdyYXRpb24tamMtOTc0IiwiayI6IjMxUjdDSXQ3OFA4MVdhU2ludjUxWVRSNSIsIm0iOnsiciI6InByb2QtZXUtd2VzdC0yIn19'